// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: tables.proto

package tables

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The embedded MLow heap window: the runtime-built table regions plus the
// table-base pointers. Stored zlib-compressed.
type HeapWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []*Region              `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	GCc           uint32                 `protobuf:"varint,2,opt,name=g_cc,json=gCc,proto3" json:"g_cc,omitempty"`
	GNrg          uint32                 `protobuf:"varint,3,opt,name=g_nrg,json=gNrg,proto3" json:"g_nrg,omitempty"`
	GPitch        uint32                 `protobuf:"varint,4,opt,name=g_pitch,json=gPitch,proto3" json:"g_pitch,omitempty"`
	GClk          uint32                 `protobuf:"varint,5,opt,name=g_clk,json=gClk,proto3" json:"g_clk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeapWindow) Reset() {
	*x = HeapWindow{}
	mi := &file_tables_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeapWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeapWindow) ProtoMessage() {}

func (x *HeapWindow) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeapWindow.ProtoReflect.Descriptor instead.
func (*HeapWindow) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{0}
}

func (x *HeapWindow) GetRegions() []*Region {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *HeapWindow) GetGCc() uint32 {
	if x != nil {
		return x.GCc
	}
	return 0
}

func (x *HeapWindow) GetGNrg() uint32 {
	if x != nil {
		return x.GNrg
	}
	return 0
}

func (x *HeapWindow) GetGPitch() uint32 {
	if x != nil {
		return x.GPitch
	}
	return 0
}

func (x *HeapWindow) GetGClk() uint32 {
	if x != nil {
		return x.GClk
	}
	return 0
}

// One contiguous heap region: its absolute base address and bytes.
type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          uint32                 `protobuf:"varint,1,opt,name=base,proto3" json:"base,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_tables_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{1}
}

func (x *Region) GetBase() uint32 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *Region) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_tables_proto protoreflect.FileDescriptor

var file_tables_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x6d, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x0a,
	0x48, 0x65, 0x61, 0x70, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x12, 0x2d, 0x0a, 0x07, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x6c,
	0x6f, 0x77, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x11, 0x0a, 0x04, 0x67, 0x5f, 0x63,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x67, 0x43, 0x63, 0x12, 0x13, 0x0a, 0x05,
	0x67, 0x5f, 0x6e, 0x72, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x67, 0x4e, 0x72,
	0x67, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x5f, 0x70, 0x69, 0x74, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x67, 0x50, 0x69, 0x74, 0x63, 0x68, 0x12, 0x13, 0x0a, 0x05, 0x67, 0x5f,
	0x63, 0x6c, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x67, 0x43, 0x6c, 0x6b, 0x22,
	0x30, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x75, 0x72, 0x70, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2f, 0x6d, 0x65, 0x6f, 0x77, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x6d, 0x6c, 0x6f, 0x77, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_tables_proto_rawDescOnce sync.Once
	file_tables_proto_rawDescData []byte
)

func file_tables_proto_rawDescGZIP() []byte {
	file_tables_proto_rawDescOnce.Do(func() {
		file_tables_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tables_proto_rawDesc), len(file_tables_proto_rawDesc)))
	})
	return file_tables_proto_rawDescData
}

var file_tables_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tables_proto_goTypes = []any{
	(*HeapWindow)(nil), // 0: mlow.tables.HeapWindow
	(*Region)(nil),     // 1: mlow.tables.Region
}
var file_tables_proto_depIdxs = []int32{
	1, // 0: mlow.tables.HeapWindow.regions:type_name -> mlow.tables.Region
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tables_proto_init() }
func file_tables_proto_init() {
	if File_tables_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tables_proto_rawDesc), len(file_tables_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tables_proto_goTypes,
		DependencyIndexes: file_tables_proto_depIdxs,
		MessageInfos:      file_tables_proto_msgTypes,
	}.Build()
	File_tables_proto = out.File
	file_tables_proto_goTypes = nil
	file_tables_proto_depIdxs = nil
}
